version: 2.1
orbs:
  node: circleci/node@3.0.0
workflows:
  tests-and-deploy:
    jobs:
      - node/test
      - build-and-deploy:
          requires:
            - node/test

  node-tests:
    jobs:
      - node/test

jobs:
  build-and-deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Build
          command: npm run build
      - run:
          name: Deploy Netlify
          command: npx netlify deploy --prod --dir=build